export const BUSINESS_CATEGORIES = [
  'Fashion & Apparel',
  'Beauty & Skincare',
  'Health & Wellness',
  'Fitness & Sports',
  'Food & Beverage',
  'Restaurants & Cafes',
  'Travel & Hospitality',
  'Hotels & Resorts',
  'Technology',
  'Electronics & Gadgets',
  'Education & EdTech',
  'Finance & FinTech',
  'Real Estate',
  'Home Decor & Furniture',
  'Stationery & Office Supplies',
  'Corporate Gifting',
  'Events & Entertainment',
  'Media & Production',
  'Gaming',
  'Automotive',
  'Jewellery & Accessories',
  'Baby & Kids',
  'Pet Care',
  'Local Services',
  'E-commerce',
  'Retail Store',
  'Co-working & Office Spaces',
  'Professional Services',
  'Non-Profit / NGO',
  'Other',
] as const;

export type BusinessCategory = (typeof BUSINESS_CATEGORIES)[number];
